export type BranchMapping = {
  posCode: string;
  posName: string;
  grabName: string | null;
  foodpandaName: string | null;
};

export const branchMappings: BranchMapping[] = [
  {
    posCode: "AMK",
    posName: "GILIGAN'S AYALA MALL MARIKINA",
    grabName: "Giligan's Restaurant - Ayala Marikina",
    foodpandaName: "Giligan's - Ayala Malls Marikina",
  },
  {
    posCode: "ANG",
    posName: "Marquee Mall",
    grabName: "Giligan's Restaurant - Ayala Marquee",
    foodpandaName: "Giligan's - Marquee Mall",
  },
  {
    posCode: "ANO",
    posName: "GILIGAN'S SM ANGONO RIZAL",
    grabName: "Giligan's Restaurant - SM Center Angono",
    foodpandaName: "Giligan's - SM Center Angono",
  },
  {
    posCode: "AOL",
    posName: "GILIGAN'S ABOITIZ OUTLET LIPA",
    grabName: null,
    foodpandaName: "Giligan's - The Outlets at Lipa",
  },
  {
    posCode: "ASP",
    posName: "GILIGAN'S AYALA SOUTHPARK",
    grabName: "Giligan's Restaurant - Ayala Mall South Park",
    foodpandaName: "Giligan's - Ayala Malls Southpark",
  },
  { posCode: "AST", posName: "GILIGAN'S AYALA MALLS SERIN", grabName: null, foodpandaName: null },
  {
    posCode: "BAC",
    posName: "GILIGAN'S SM CITY BACOLOD",
    grabName: "Giligan's Restaurant - SM City Bacolod",
    foodpandaName: "Giligan's - SM City Bacolod",
  },
  {
    posCode: "BAG",
    posName: "Giligan's Baguio",
    grabName: "Giligan's Restaurant - Baguio City",
    foodpandaName: "Giligan's - Baguio City",
  },
  {
    posCode: "BAL",
    posName: "GILIGAN'S SM BALIWAG",
    grabName: "Giligan's Restaurant - SM Baliwag",
    foodpandaName: "Giligan's - SM City Baliwag",
  },
  {
    posCode: "BAT",
    posName: "GILIGAN'S SM BATANGAS CITY",
    grabName: null,
    foodpandaName: "Giligan's - SM City Batangas",
  },
  {
    posCode: "CAB",
    posName: "GILIGAN'S SM CABANATUAN",
    grabName: null,
    foodpandaName: "Giligan's - SM City Cabanatuan",
  },
  {
    posCode: "CAL",
    posName: "GILIGAN'S SM CALAMBA",
    grabName: "Giligan's Restaurant - SM Calamba",
    foodpandaName: "Giligan's - SM City Calamba",
  },
  {
    posCode: "CHR",
    posName: "GILIGAN'S SM CHERRY ANTIPOLO",
    grabName: "Giligan's Restaurant - SM Cherry Antipolo",
    foodpandaName: "Giligan's - SM Cherry Antipolo",
  },
  {
    posCode: "CIR",
    posName: "GILIGAN'S CIRCULO VERDE",
    grabName: "Giligan's Restaurant - Circulo Verde",
    foodpandaName: "Giligan's - Circulo Verde",
  },
  {
    posCode: "CLK",
    posName: "GILIGAN'S SM CITY CLARK",
    grabName: "Giligan's Restaurant - SM City Clark",
    foodpandaName: "Giligan's - SM Clark",
  },
  {
    posCode: "CM1",
    posName: "GILIGAN'S CIRCUIT MAKATI",
    grabName: "Giligan's Restaurant - Circuit Makati",
    foodpandaName: "Giligan's - Circuit",
  },
  {
    posCode: "FEX",
    posName: "GILIGAN'S FESTIVAL EXPANSION",
    grabName: "Giligan's Restaurant - Festival Mall Extension",
    foodpandaName: "Giligan's - Festival Mall Extension",
  },
  {
    posCode: "GBR",
    posName: "GILIGAN'S GAISANO BINANGONAN RIZAL",
    grabName: "Giligan's Restaurant - Gaisano Binagonan Rizal",
    foodpandaName: null,
  },
  {
    posCode: "GHL",
    posName: "GILIGAN'S GREENHILLS",
    grabName: "Giligan's Restaurant - Greenhills",
    foodpandaName: "Giligan's - Greenhills",
  },
  { posCode: "GIR", posName: "GILIGAN'S GAISANO IRIGA", grabName: null, foodpandaName: null },
  { posCode: "HEC", posName: "GILIGAN'S HYPERMARKET CUBAO", grabName: null, foodpandaName: null },
  {
    posCode: "HFT",
    posName: "GILIGAN'S HYPERMARKET FTI",
    grabName: "Giligan's Restaurant - SM Hypermarket FTI",
    foodpandaName: "Giligan's - SM Hypermarket FTI",
  },
  {
    posCode: "HIC",
    posName: "GILIGAN'S HYPERMARKET IMUS CAVITE",
    grabName: "Giligan's Restaurant - SM Hypermarket Imus",
    foodpandaName: null,
  },
  {
    posCode: "HQN",
    posName: "GILIGAN'S SM HYPERMARKET NOVALICHES",
    grabName: null,
    foodpandaName: null,
  },
  {
    posCode: "HSL",
    posName: "GILIGAN'S HYPERMARKET SUCAT-LOPEZ",
    grabName: "Giligan's Restaurant - SM Hypermarket Sucat-Lopez",
    foodpandaName: "Giligan's - SM Hypermarket Sucat",
  },
  {
    posCode: "IL2",
    posName: "GILIGAN'S SM CITY ILOILO",
    grabName: "Giligan's Restaurant - SM Iloilo Southpoint",
    foodpandaName: "Giligan's - SM City Iloilo Southpoint",
  },
  {
    posCode: "IMU",
    posName: "GILIGAN'S 5M IMUS",
    grabName: "Giligan's Restaurant - SM Center Imus",
    foodpandaName: "Giligan's - SM Center Imus",
  },
  {
    posCode: "JAC",
    posName: "GILIGAN'S JACKMAN PLAZA MUNOZ",
    grabName: "Giligan's Restaurant - Jackman Plaza Munoz",
    foodpandaName: "Giligan's - Jackman Plaza Munoz",
  },
  {
    posCode: "LCI",
    posName: "GILIGAN'S LANCASTER CITY IMUS",
    grabName: "Giligan's Restaurant - Lancaster Imus",
    foodpandaName: "Giligan's - Lancaster",
  },

  { posCode: "LEM", posName: "GILIGAN'S 5M LEMERY", grabName: null, foodpandaName: null },
  {
    posCode: "LIP",
    posName: "ROBINSONS PLACE LIPA",
    grabName: "Giligan's Restaurant - Robinsons Lipa",
    foodpandaName: "Giligan's - Robinsons Lipa",
  },
  {
    posCode: "LOR",
    posName: "GILIGAN'S SAN LORENZO PLACE",
    grabName: "Giligan's Restaurant - San Lorenzo Place Makati",
    foodpandaName: "Giligan's - San Lorenzo Place",
  },
  {
    posCode: "LUC",
    posName: "GILIGAN'S SM LUCENA",
    grabName: null,
    foodpandaName: "Giligan's - SM City Lucena",
  },
  {
    posCode: "MAR",
    posName: "Market! Market!",
    grabName: "Giligan's Restaurant - Ayala Market Market",
    foodpandaName: "Giligan's - Fiesta Market BGC",
  },
  {
    posCode: "MIL",
    posName: "GILIGAN'S MILLE LUCE",
    grabName: "Giligan's Restaurant - Mille Luce Antipolo",
    foodpandaName: null,
  },
  {
    posCode: "MOA",
    posName: "SM by the Bay",
    grabName: "Giligan's Restaurant - SM Mall of Asia",
    foodpandaName: "Giligan's - MOA",
  },
  { posCode: "MOD", posName: "GILIGAN'S MOADTO STRIP MALL", grabName: null, foodpandaName: null },
  {
    posCode: "MSM",
    posName: "GILIGAN'S MAIN SQUARE MOLINO",
    grabName: "Giligan's Restaurant - Main Square Molino",
    foodpandaName: "Giligan's - Main Square",
  },
  {
    posCode: "MUN",
    posName: "GILIGAN'S SM CENTER MUNTINLUPA",
    grabName: "Giligan's Restaurant - SM Center Muntinlupa",
    foodpandaName: "Giligan's - SM Center Muntinlupa",
  },
  {
    posCode: "NOR",
    posName: "GILIGAN'S SMNE SKY GARDEN",
    grabName: "Giligan's Restaurant - SM City North Edsa",
    foodpandaName: "Giligan's - SM City North Edsa",
  },
  {
    posCode: "NOV",
    posName: "GILIGAN'S SM NOVALICHES",
    grabName: "Giligan's Restaurant - SM Novaliches",
    foodpandaName: "Giligan's - SM City Novaliches",
  },
  {
    posCode: "NPC",
    posName: "GILIGAN'S NEWPORT CITY",
    grabName: "Giligan's Restaurant - Newport City",
    foodpandaName: null,
  },
  { posCode: "NPN", posName: "GILIGAN'S NOVA PLAZA MALL", grabName: null, foodpandaName: null },

  {
    posCode: "OMV",
    posName: "GILIGAN'S ONEMALL VALENZUELA",
    grabName: "Giligan's Restaurant - One Mall Valenzuela",
    foodpandaName: "Giligan's - One Mall Valenzuela",
  },
  {
    posCode: "PAC",
    posName: "GILIGAN'S PACO MALL",
    grabName: "Giligan's Restaurant - Paco Mall",
    foodpandaName: null,
  },
  {
    posCode: "PCJ",
    posName: "PUREGOLD CAINTA JUNCTION",
    grabName: "Giligan's Restaurant - Puregold Cainta Junction",
    foodpandaName: "Giligan's - Puregold Cainta",
  },
  {
    posCode: "PED",
    posName: "GILIGAN'S ROBINSONS SAN PEDRO",
    grabName: "Giligan's Restaurant - Robinsons Galleria South",
    foodpandaName: "Giligan's - Robinsons Galleria South",
  },
  {
    posCode: "PSG",
    posName: "GILIGAN'S SM PASIG",
    grabName: "Giligan's Restaurant - SM Center Pasig",
    foodpandaName: "Giligan's - SM Center Pasig",
  },
  {
    posCode: "PUL",
    posName: "GILIGAN'S SM PULILAN",
    grabName: "Giligan's Restaurant - SM Center Pulilan",
    foodpandaName: null,
  },
  {
    posCode: "RBC",
    posName: "GILIGAN'S THE PLAZA BAGONG SILANG",
    grabName: null,
    foodpandaName: null,
  },
  {
    posCode: "REA",
    posName: "GILIGAN'S ROBINSONS PLACE ANTIPOLO",
    grabName: null,
    foodpandaName: null,
  },
  { posCode: "RGT", posName: "GILIGAN'S ROBINSONS GEN TRIAS", grabName: null, foodpandaName: null },
  {
    posCode: "RIV",
    posName: "GILIGAN'S RIVERBANKS MARIKINA",
    grabName: "Giligan's Restaurant - Riverbanks Center Marikina",
    foodpandaName: null,
  },
  {
    posCode: "RNG",
    posName: "GILIGAN'S ROBINSONS NAGA",
    grabName: null,
    foodpandaName: "Giligan's - Robinsons Naga",
  },
  { posCode: "SCL", posName: "GILIGAN'S SM CENTER LAS PIÑAS", grabName: null, foodpandaName: null },
  {
    posCode: "SDH",
    posName: "GILIGAN'S DAANG HARI",
    grabName: "Giligan's Restaurant - Vista Mall Daang Hari",
    foodpandaName: "Giligan's - Vista Mall Daang Hari",
  },
  {
    posCode: "SFV",
    posName: "GILIGAN'S SM FAIRVIEW",
    grabName: "Giligan's Restaurant - SM City Fairview",
    foodpandaName: "Giligan's - SM City Fairview",
  },
  {
    posCode: "SGD",
    posName: "GILIGAN'S SM SANGANDAAN",
    grabName: "Giligan's Restaurant - SM Center Sangandaan",
    foodpandaName: "Giligan's - SM Center Sangandaan",
  },
  {
    posCode: "SLE",
    posName: "GILIGAN'S IL CENTRO",
    grabName: "Giligan's Restaurant - Santa Lucia East Grand Mall",
    foodpandaName: "Giligan's - Sta Lucia East Mall",
  },
  {
    posCode: "SML",
    posName: "GILIGAN'S SM CITY MOLINO",
    grabName: "Giligan's Restaurant - SM Center Molino",
    foodpandaName: "Giligan's - SM Center Molino",
  },
  {
    posCode: "SOU",
    posName: "GILIGAN'S SOUTHMALL",
    grabName: "Giligan's Restaurant - SM City Southmall",
    foodpandaName: "Giligan's - SM Southmall",
  },
  {
    posCode: "SPP",
    posName: "GILIGAN'S SM CITY PUERTO PRINCESA",
    grabName: null,
    foodpandaName: "Giligan's - SM City Puerto Princesa",
  },
  {
    posCode: "SRC",
    posName: "GILIGAN'S SM ROSARIO",
    grabName: "Giligan's Restaurant - SM Rosario",
    foodpandaName: "Giligan's - SM City Rosario",
  },
  {
    posCode: "SSJ",
    posName: "GILIGAN'S SM SAN JOSE BRANCH",
    grabName: "Giligan's Restaurant - SM San Jose Del Monte",
    foodpandaName: null,
  },
  {
    posCode: "SSP",
    posName: "GILIGAN'S SM SAN PEDRO",
    grabName: "Giligan's Restaurant - SM Center San Pedro",
    foodpandaName: null,
  },
  {
    posCode: "SSS",
    posName: "GILIGAN'S SM SEASIDE CEBU",
    grabName: "Giligan's Restaurant - SM Seaside Cebu",
    foodpandaName: "Giligan's - SM Seaside City Cebu",
  },
  {
    posCode: "STG",
    posName: "GILIGAN'S STARMALL TAGUIG",
    grabName: "Giligan's Restaurant - Starmall Taguig",
    foodpandaName: "Giligan's - Starmall Taguig",
  },
  {
    posCode: "SWM",
    posName: "GILIGAN'S SOUTHWOODS MALL",
    grabName: "Giligan's Restaurant - Southwoods Mall Binan",
    foodpandaName: "Giligan's  - Southwoods Mall",
  },
  {
    posCode: "TAG",
    posName: "GILIGAN'S TAGAYTAY",
    grabName: "Giligan's Restaurant - Robinsons Tagaytay",
    foodpandaName: "Giligan's - Robinsons Place Tagaytay",
  },
  {
    posCode: "TAY",
    posName: "GILIGAN'S SM TAYTAY",
    grabName: "Giligan's Restaurant - SM Taytay",
    foodpandaName: "Giligan's - SM City Taytay",
  },
  {
    posCode: "TEL",
    posName: "GILIGAN'S SM TELABASTAGAN",
    grabName: "Giligan's Restaurant - SM Telebastagan",
    foodpandaName: "Giligan's - SM City Telebastagan",
  },
  {
    posCode: "VAL",
    posName: "GILIGAN'S SM CITY VALENZUELA",
    grabName: "Giligan's Restaurant - SM Valenzuela",
    foodpandaName: "Giligan's - SM City Valenzuela",
  },
  {
    posCode: "VER",
    posName: "GILIGAN'S VERDANT",
    grabName: "Giligan's Restaurant - Verdant Strip",
    foodpandaName: "Giligan's - Verdant Strip Mall",
  },
  {
    posCode: "VMB",
    posName: "GILIGAN'S VISTAMALL MALOLOS",
    grabName: "Giligan's Restaurant - Vista Mall Malolos",
    foodpandaName: "Giligan's - Vista Mall Malolos",
  },
  {
    posCode: "VMD",
    posName: "GILIGAN'S VISTAMALL DASMARINAS",
    grabName: "Giligan's Restaurant - Vista Mall Dasmarinas",
    foodpandaName: "Giligan's - Vista Mall Dasmarinas",
  },
  {
    posCode: "VMS",
    posName: "GILIGAN'S VICTORY MALL STA. ROSA",
    grabName: null,
    foodpandaName: null,
  },
  {
    posCode: "VST",
    posName: "GILIGAN'S VISTAMALL SAN FERNANDO",
    grabName: "Giligan's Restaurant - Vista Mall San Fernando",
    foodpandaName: null,
  },
  {
    posCode: "VSP",
    posName: "GILIGAN'S VILLAR SIPAG",
    grabName: "Giligan's Restaurant - Villar Sipag Las Pinas",
    foodpandaName: "Giligan's - Pulang Lupa",
  },
  {
    posCode: "VSR",
    posName: "GILIGAN'S VISTAMALL SANTA ROSA",
    grabName: "Giligan's Restaurant - Vista Mall Santa Rosa",
    foodpandaName: "Giligan's - Vista Mall Santa Rosa",
  },
  {
    posCode: "VTZ",
    posName: "GILIGAN'S VISTAMALL TANZA",
    grabName: "Giligan's Restaurant - Vista Mall Tanza",
    foodpandaName: null,
  },
  { posCode: "WNB", posName: "GILIGAN'S WALTERMART NASUGBU", grabName: null, foodpandaName: null },
  { posCode: "WPT", posName: "GILIGAN'S WM PANIQUI", grabName: null, foodpandaName: null },
  {
    posCode: "WSM",
    posName: "GILIGAN'S WALTERMART STA.MARIA",
    grabName: "Giligan's Restaurant - Walter Mart Sta. Maria",
    foodpandaName: "Giligan's - Walter Mart Santa Maria",
  },
  {
    posCode: "WVA",
    posName: "GILIGAN'S WILCON CITY CENTER",
    grabName: "Giligan's Restaurant - Wilcon Visayas Avenue",
    foodpandaName: "Giligan's - Wilcon City Center",
  },
];
